namespace PluginCommon.Localization
{
    public enum PluginLocalziationKey
    {
        OK,
        Cancel,
        ExposureTime,
        IntervalMs,
        ViewportArea,
        Live,
        Snapshot,
        Capture,
        CameraControl,
        CameraConfig,
        Auto,
        Gain,
        BlackLevel,
        Original,
        RFromROI,
        TimeSeries,
        Interval,
        Duration,
        Frames,
        TriggerMode,
        Format,
        TimeSeriesAutoExposure,
        HotPixel,

        Histogram,
        Profile,
        Rectangle,
        Oval,
        Statistics,
        FlipH,
        FlipV,
        Ruler,
        ColorImg,
        SetR2Win,
        FitImg2Win,
        ResetPos,

        Log,
        Gamma,
        Min,
        Max,
        Reset,
        LineW,
        Export,
        Default,

        //Settings panel
        RegionSettings,
        Top,
        Left,
        Bottom,
        Right,
        FullFrame,
        CameraSettings,
        Bin,
        TimeSeriesCO,
        DurationEditable,
        FramesEditable,
        HardareTrigger,
        ColorImageType,
        LEDIndicator,
        EnableCapturingImageUpdate,

        //Ruler Configuration Window
        MainPaletteHeaderText,
        StandardPaletteHeaderText,
        RulerConfiguration,
        Font,
        LineWidth,
        Color,
        PanelOpacity,
        Placement,
        BottomLeft,
        BottomRight,
        TopLeft,
        TopRight,

        Play,
        Stop,
        SaveAs,
        ShowScale,

        CH,
        Area,
        Perimeter,
        Mean,
        StdDev,

        AxisIntensity,
        AxisIndex,
        HistEmpty,
        DrawProfileLine,

        HistOptions,
        SepRGBHist,
        NormalizeBin,

        PrefixName,
        FrameRate,

        Objective,
        XAxis,
        UnitUm,
        UnitPx,

        ManualC,
        LoadImage,
        CombineImages,
        CombineTip,
        Browse,
    }
}
