//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Configuration;
using FilterWheelShared.Common;

namespace Viewport.Properties {


    [SettingsProvider(typeof(CustomSettingsProvider))]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.2.0.0")]
    internal sealed partial class RulerConfigurationSettings : global::System.Configuration.ApplicationSettingsBase
    {

        private static RulerConfigurationSettings defaultInstance = ((RulerConfigurationSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new RulerConfigurationSettings())));

        public static RulerConfigurationSettings Default
        {
            get
            {
                return defaultInstance;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Segoe UI")]
        public global::System.Windows.Media.FontFamily FontFamily
        {
            get
            {
                return ((global::System.Windows.Media.FontFamily)(this["FontFamily"]));
            }
            set
            {
                this["FontFamily"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16")]
        public double FontSize
        {
            get
            {
                return ((double)(this["FontSize"]));
            }
            set
            {
                this["FontSize"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF000000")]
        public global::System.Windows.Media.Color FontColor
        {
            get
            {
                return ((global::System.Windows.Media.Color)(this["FontColor"]));
            }
            set
            {
                this["FontColor"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int LineWidth
        {
            get
            {
                return ((int)(this["LineWidth"]));
            }
            set
            {
                this["LineWidth"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF000000")]
        public global::System.Windows.Media.Color LineColor
        {
            get
            {
                return ((global::System.Windows.Media.Color)(this["LineColor"]));
            }
            set
            {
                this["LineColor"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int PanelOpacity
        {
            get
            {
                return ((int)(this["PanelOpacity"]));
            }
            set
            {
                this["PanelOpacity"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFFFFFF")]
        public global::System.Windows.Media.Color PanelColor
        {
            get
            {
                return ((global::System.Windows.Media.Color)(this["PanelColor"]));
            }
            set
            {
                this["PanelColor"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BottomRight")]
        public global::DrawingTool.Factory.RelativePlacement ScalerPlacement
        {
            get
            {
                return ((global::DrawingTool.Factory.RelativePlacement)(this["ScalerPlacement"]));
            }
            set
            {
                this["ScalerPlacement"] = value;
            }
        }

    }
}
